Allow https metadata without credentials
OData/lab pull request #67
Opened 2017-09-14 16:38 UTC by Gabee01

[Issue 56](https://github.com/OData/lab/issues/56)

2017-09-14 16:38 UTC, msftclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-09-15 23:31 UTC, AlanWong-MS commented on ODataConnectedService/src/ViewModels/ConfigODataEndpointViewModel.cs
> +            ServicePointManager.ServerCertificateValidationCallback += new System.Net.Security.RemoteCertificateValidationCallback((s, ce, ch, ssl) => true);
Is this meant for test/development environment only, or have you encountered issues outside of the development process?

In either case, we should add some guards inside the lambda. We should add a boolean such as isDevelopment which returns true as presented in your code. We should also add validation when isDevelopment == false. I would also recommend using more descriptive variable names. Below is my comprehensive suggestion:

2017-09-15 23:37 UTC, AlanWong-MS requested changes
Great start. Let's add some validations to it.

2017-11-08 20:01 UTC, nla-brandonjames commented
He has deleted this repository

2017-11-08 20:45 UTC, AlanWong-MS commented
Closing this PR due to contributor's repo deletion.

2017-11-08 20:45 UTC, closed without merging

2018-05-02 08:06 UTC, onyangofred commented
Just open the link in Internet explorer, will prompt for username and password. Then save the credentials. Try again in visual studio. It works!!!